// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_constructor = "CgkIqIqqjZYFEAIQEw"; // <GPGSID>
        public const string achievement_slow_but_steady = "CgkIqIqqjZYFEAIQCA"; // <GPGSID>
        public const string achievement_thinking_with_portals = "CgkIqIqqjZYFEAIQEQ"; // <GPGSID>
        public const string achievement_endgame = "CgkIqIqqjZYFEAIQAQ"; // <GPGSID>
        public const string achievement_shoplifter = "CgkIqIqqjZYFEAIQBQ"; // <GPGSID>
        public const string achievement_forever_number_two = "CgkIqIqqjZYFEAIQDg"; // <GPGSID>
        public const string achievement_this_is_complicated = "CgkIqIqqjZYFEAIQDA"; // <GPGSID>
        public const string leaderboard_test_highscore = "CgkIqIqqjZYFEAIQAg"; // <GPGSID>
        public const string achievement_flipper = "CgkIqIqqjZYFEAIQFA"; // <GPGSID>
        public const string achievement_arrow_to_the_knee = "CgkIqIqqjZYFEAIQBw"; // <GPGSID>
        public const string achievement_khajiit_has_wares = "CgkIqIqqjZYFEAIQCw"; // <GPGSID>
        public const string achievement_gotta_go_fast = "CgkIqIqqjZYFEAIQEg"; // <GPGSID>
        public const string achievement_death_is_my_hobby = "CgkIqIqqjZYFEAIQCg"; // <GPGSID>
        public const string achievement_vip = "CgkIqIqqjZYFEAIQEA"; // <GPGSID>
        public const string achievement_starhunter = "CgkIqIqqjZYFEAIQDw"; // <GPGSID>
        public const string achievement_attracted_to_you = "CgkIqIqqjZYFEAIQBg"; // <GPGSID>
        public const string achievement_charlie_sheen = "CgkIqIqqjZYFEAIQFQ"; // <GPGSID>

}

