// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_level_9 = "CgkIqIqqjZYFEAIQHw"; // <GPGSID>
        public const string achievement_video_junkie = "CgkIqIqqjZYFEAIQEQ"; // <GPGSID>
        public const string achievement_shoplifter = "CgkIqIqqjZYFEAIQEA"; // <GPGSID>
        public const string leaderboard_level_10 = "CgkIqIqqjZYFEAIQIA"; // <GPGSID>
        public const string achievement_flipper = "CgkIqIqqjZYFEAIQFA"; // <GPGSID>
        public const string achievement_khajiit_has_wares = "CgkIqIqqjZYFEAIQBg"; // <GPGSID>
        public const string achievement_death_is_my_hobby = "CgkIqIqqjZYFEAIQCg"; // <GPGSID>
        public const string leaderboard_level_11 = "CgkIqIqqjZYFEAIQIQ"; // <GPGSID>
        public const string leaderboard_level_12 = "CgkIqIqqjZYFEAIQIg"; // <GPGSID>
        public const string leaderboard_level_13 = "CgkIqIqqjZYFEAIQIw"; // <GPGSID>
        public const string leaderboard_level_14 = "CgkIqIqqjZYFEAIQJA"; // <GPGSID>
        public const string leaderboard_level_15 = "CgkIqIqqjZYFEAIQJQ"; // <GPGSID>
        public const string leaderboard_level_16 = "CgkIqIqqjZYFEAIQJg"; // <GPGSID>
        public const string leaderboard_level_17 = "CgkIqIqqjZYFEAIQJw"; // <GPGSID>
        public const string leaderboard_level_18 = "CgkIqIqqjZYFEAIQKA"; // <GPGSID>
        public const string leaderboard_level_19 = "CgkIqIqqjZYFEAIQKQ"; // <GPGSID>
        public const string achievement_slow_but_steady = "CgkIqIqqjZYFEAIQCA"; // <GPGSID>
        public const string achievement_first_steps = "CgkIqIqqjZYFEAIQBw"; // <GPGSID>
        public const string achievement_constructor = "CgkIqIqqjZYFEAIQAQ"; // <GPGSID>
        public const string leaderboard_level_20 = "CgkIqIqqjZYFEAIQKg"; // <GPGSID>
        public const string leaderboard_level_21 = "CgkIqIqqjZYFEAIQKw"; // <GPGSID>
        public const string leaderboard_level_22 = "CgkIqIqqjZYFEAIQLA"; // <GPGSID>
        public const string leaderboard_level_23 = "CgkIqIqqjZYFEAIQLQ"; // <GPGSID>
        public const string leaderboard_level_24 = "CgkIqIqqjZYFEAIQLg"; // <GPGSID>
        public const string leaderboard_level_25 = "CgkIqIqqjZYFEAIQLw"; // <GPGSID>
        public const string leaderboard_level_26 = "CgkIqIqqjZYFEAIQMA"; // <GPGSID>
        public const string achievement_supporter = "CgkIqIqqjZYFEAIQBQ"; // <GPGSID>
        public const string achievement_we_are_number_one = "CgkIqIqqjZYFEAIQFQ"; // <GPGSID>
        public const string achievement_reset_button = "CgkIqIqqjZYFEAIQFg"; // <GPGSID>
        public const string leaderboard_level_1 = "CgkIqIqqjZYFEAIQFw"; // <GPGSID>
        public const string leaderboard_level_2 = "CgkIqIqqjZYFEAIQGA"; // <GPGSID>
        public const string leaderboard_level_3 = "CgkIqIqqjZYFEAIQGQ"; // <GPGSID>
        public const string leaderboard_level_4 = "CgkIqIqqjZYFEAIQGg"; // <GPGSID>
        public const string leaderboard_level_5 = "CgkIqIqqjZYFEAIQGw"; // <GPGSID>
        public const string leaderboard_level_6 = "CgkIqIqqjZYFEAIQHA"; // <GPGSID>
        public const string leaderboard_level_7 = "CgkIqIqqjZYFEAIQHQ"; // <GPGSID>
        public const string leaderboard_level_8 = "CgkIqIqqjZYFEAIQHg"; // <GPGSID>

}

